[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "docx>=0.2.4",
    "flask>=3.1.2",
    "fpdf2>=2.8.4",
    "matplotlib>=3.10.6",
    "python-docx>=1.2.0",
    "reportlab>=4.4.3",
]
